format_version: v1.0
type: UniqueComponent
attributes: {id: ThreadX}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: THREADX_CPU_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ThreadX, value: '200000000'}
  - type: Integer
    attributes: {id: THREADX_PERIPHERAL_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ThreadX, value: '100000000'}
- type: ElementPosition
  attributes: {x: '1', y: '87', id: ThreadX}
